image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master
    - dev

.test:
  stage:  test
  image: node:18
  before_script:
    - yarn config set registry https://registry.npmmirror.com
    - yarn install

style-test:
  extends: .test
  allow_failure: true
  script:
    - node_modules/eslint/bin/eslint.js

deploy:
  stage: deploy
  script:
    - deployer dyno replace frontend $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG gitlab-ci-token $REGISTRY_PWD
  only:
    - master
    - dev
